add monitoring

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -33,6 +33,12 @@ jobs:
         run: |
           sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_HOST"@139.180.158.237 << 'EOF'
             
+            if ! command -v git &> /dev/null
+            then
+              echo "Git not found, installing..."
+              sudo apt-get update && sudo apt-get install -y git
+            fi
+
             if [ ! -d "cyberskill" ]; then
               echo "Creating directory cyberskill"
               mkdir -p cyberskill
